---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(magrittr)
```

```{r}
# Make the url for downloading the data file 
# 
# Args: 
#   year: the year of the data file 
#   quarter: the quarter of the data file 
# 
# Returns: 
#   The url of the file name 
make_urls <- function(year, quarter) {
 paste0(
   "https://projects.propublica.org/congress/assets/staffers/", year, "Q", quarter,  "-house-disburse-detail.csv"
   )
}

# Make vectors of years and quarters
years <- c(rep("2016", 4))
quarters <- c(1:4)

# Make a list of urls
urls <- map2(years, quarters, make_urls)
```

```{r}
all_data <- map(urls, read_csv)
```

```{r}
# Add a filename vector
# TODO make a nicer filename vector
add_fnames <- function(dfs, names) {
  dfs %>% mutate(file = paste0(names))
}

# Summarise mean
get_mean <- function(dfs) {
  dfs %>% 
    group_by(file, CATEGORY) %>% 
    summarise(mean = mean(AMOUNT, na.rm = T))
}

# Make a dataframe of file names and means
all_data2 <- map2(all_data, urls, add_fnames) %>% 
  map(., get_mean) %>% 
  # TODO make nicer variable names
  map_df(extract, c("file", "CATEGORY", "mean"))
```