---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plyr) #make sure to load this before tidyverse because plyr causes issues if it's loaded after dplyr
library(tidyverse)
library(magrittr)
```

```{r make URLs}
# Make the url for downloading the data file 
# 
# Args: 
#   year: the year of the data file 
#   quarter: the quarter of the data file 
# 
# Returns: 
#   The url of the file name 
make_urls <- function(year, quarter) {
 paste0(
   "https://projects.propublica.org/congress/assets/staffers/", year, "Q", quarter,  "-house-disburse-detail.csv"
   )
}

# Make vectors of years and quarters
years <- c(rep("2016", 4))
quarters <- c(1:4)

# Make a list of urls
urls <- map2(years, quarters, make_urls)
```

```{r read data}
all_data <- map(urls, read_csv)
```

```{r filename vector function}
add_fnames <- function(dfs, names) {
  # Adds a column of filenames 
  # 
  # Args: 
  #  dfs: a list of datasets 
  #  names: a list of file names 
  # 
  # Returns: 
  #   A list of datasets that have a file name vector
  dfs %>% mutate(file = paste0(names))
}
```

```{r function for getting mean spending}
get_mean <- function(dfs) {
  # Summarises a dataset by mean spending in each category 
  # 
  # Args: 
  #   dfs: a list of datasets 
  # 
  # Returns: 
  #   A list of datasets summarising average spending in each category
  dfs %>% 
    rename(category = CATEGORY) %>%
    group_by(file, category) %>% 
    summarise(avg_spend = mean(AMOUNT, na.rm = T))
}
```

```{r mean spending dataset}
# Make file names 
short_names <- map2(years, quarters, ~paste0(.x, "_Q", .y))

# Make a dataframe of file names and means
all_data2 <- map2(all_data, short_names, add_fnames) %>% 
  map(., get_mean) %>% 
  map_df(extract, c("file", "category", "avg_spend"))
```

```{r write to csv}
# Write to CSV 
write_csv(all_data2, path = file.path(getwd(), "loop_test_output.csv"))
```

```{r}

# This shows that there are actually two "versions" of spelling used for "Rent, Communication, Utilities":
    # 1) RENT COMMUNICATION UTILITIES (no commas used)
    # 2) RENT, COMMUNICATION, UTILITIES (2 commas used)
View(all_data2 %>% 
       ungroup() %>% 
       select(category) %>% 
       distinct() %>% 
       arrange(category)
     )

# This doesn't affect your analyses as the two versions are used in different quarters, but if you were to do
# the same computation of average spending by year, you'll get undesirable results, as you'll have one row for
# "no commas used" and one row for "2 commas used".

All_Quarters_2016 <- rbind.fill(all_data)


View(All_Quarters_2016 %>%
       group_by(CATEGORY) %>% 
       summarise(avg_spend = mean(AMOUNT, na.rm = TRUE)
                 ) %>% 
       arrange(CATEGORY)
     )
```
